### ISSUE TITLE
Store location to improve user experience on map landing

### ISSUE THREAD

**Issue by ronw98** [MovnaTeam/movna#20]
When the user lands on the map, the map is centered on paris.
![image](https://github.com/MovnaTeam/movna/assets/44091831/216b6364-3c3d-4568-a44c-d04452afcc95)

The goal of this ticket is to store and use the last known coordinates to center the map on these coordinates instead of paris.

Depends on #11 to be finished

**Comment by BriceCroix** [comment]
geolocator provides at method `lastKnownPosition` to do this, we have to add this to datasource, repository, and use-case.
